### ISSUE TITLE
[Suggestion] About the "Comparison" tab

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#61] opened 2019-03-28 11:35 UTC
This is to make comparing two designs easier. Maybe compare the previous design and the current design?

Off-topic: (I could PM you in the forum if you like that better):
It seems that you are trying to avoid using uncommon words. I actually like to see some (not too much) uncommon words (like "confess" and "tentatively" that you mentioned before) so that I can also gradually increase my vocab. As for my English skills, I believe that I can deal with a few new words without much problem.

**Comment by MauveCloud** [comment] 2019-03-28 23:31
> It seems that you are trying to avoid using uncommon words.

I don't think that's deliberate on my part.  However, I see little purpose in using fancy words unnecessarily - https://tvtropes.org/pmwiki/pmwiki.php/Main/SesquipedalianLoquaciousness explains better than I can why that can be a bad idea.

> This is to make comparing two designs easier. Maybe compare the previous design and the current design?

Could you please be more specific about the use-case here?  It seems like what you describe can technically already be done with two instances of the planner, so I'm not sure whether you're asking for a more convenient way to do that, or something else.

**Comment by KrisBigK** [comment] 2019-03-29 10:31
It is easy to compare multiple designs in one aspect, but it is difficult to see multiple differences straight away, especially when they are in different tabs. 

For example, if I want to see the difference between
`03000A120D0C0D110A03030C0D0C0D0C0D12020C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D110A110D0C0D110A11|fsn`
and
`0303030C0D120D0C0D0C020C0D0C0A0C0A140D0C0D0C0D0C0D0C0D120A0C0D0C0D0C0D0C0D0C0A0C0D0C0D0C0D0C0D120D0C0D110A11|fsn`
it is kind of difficult to find out the differences even in the simulation tab.

**Comment by MauveCloud** [comment] 2019-03-29 20:32
Sorry, I'm still vague on what you're requesting here.  If you have enough screen "real estate", you can run two instances of the planner side by side (with some overlap), or maybe vertically, depending on what you want to compare.  Example:
![TwoPlannersSideBySide](https://user-images.githubusercontent.com/8942955/55260653-2edd4a00-5226-11e9-8515-0c93d22163e0.png)
Admittedly, some users might not have enough screen resolution to do that, but what sort of content would be on this proposed "Comparison" tab to make it more useful than switching between two instances of the planner?

**Comment by KrisBigK** [comment] 2019-03-30 02:47
![image](https://user-images.githubusercontent.com/34199560/55270349-b6839100-52d8-11e9-8c20-2c626d04336a.png)

An example of what I hope it to look like. I just want to show the idea so I didn't put all differences in there. The reactor temperature-related things are arguable whether it is good or not. The code input within this tab is for the second design that is compared with.

**Comment by MauveCloud** [comment] 2019-03-31 16:55
Okay, this will be time-consuming to implement, and I can already see a few details that need ironing out:
1. It is not obvious which way the comparison is going.
2. Is this running a new simulation as soon as a new code is pasted in?  Your original wording was "compare the previous design and the current design" - if the code field is read-only and shows the reactor code of the previously-run simulation, that might be faster and also reduce possible confusion about the direction of comparison.
3. What should the comparison show for incompatible details, such as comparing an EU reactor with a fluid reactor?
4. Have you come up with rules for the color-coding?

**Comment by KrisBigK** [comment] 2019-03-31 23:13
1. You could mention that it is the in-grid one compared with in-tab one (in-grid one is to the left)
2. I suggest that it is simulated when the simulate button is clicked. I don't think that it is good to show the previously-run simulation, because when comparing, you are going to change the in-grid one and simulate it anyways. The read-only idea is nice.
3. Show "Incompatible: ..." in black, maybe?
4. My ideas:
Green for the good changes (output becomes higher, needs less materials, etc)
Yellow/orange for the unchanged
Red for the bad changes

**Comment by MauveCloud** [comment] 2019-04-07 16:37
I have tentatively implemented this, but I expect you might want some additional adjustments, so I'm leaving the issue open for now.  If by some miracle, you're happy with it as-is, you can close it yourself.

**Comment by KrisBigK** [comment] 2019-04-08 12:12
Could you add an option for only showing the different data (those that aren't in orange)? Most of the times one is just focused on the different data.

I would like an option for locking the code in-tab. This is needed especially when trying to improve the current design and wanting the design being compared unchanged.

I noticed that the data in the comparison tab can't be selected, unlike those in the simulation tab. Is that caused by it being in a JLabel and wrapped in html tags? (according to your comment in bundle.properties) A button for copying those data would be helpful.

Another thing, the reactor temperature. I don't think the current displayed colors of reactor temperature is proper for all designs, but I don't have a clear idea how they should be changed since whether it is beneficial for the reactor temperature to be higher or not highly depends on what the designer want. For pure uranium/thorium designs it is better to have a lower max temperature, while for a MOX reactor it might be better to have a higher max temperature. Hybrid reactors get more complex with this.

**Comment by MauveCloud** [comment] 2019-04-08 17:38
> Could you add an option for only showing the different data (those that aren't in orange)? Most of the times one is just focused on the different data.

Tricky (especially since some of the details do not have separate resource bundle entries at the moment), but I'll look into this.

> I would like an option for locking the code in-tab. This is needed especially when trying to improve the current design and wanting the design being compared unchanged.

That should be fairly simple to add.

> I noticed that the data in the comparison tab can't be selected, unlike those in the simulation tab. Is that caused by it being in a JLabel and wrapped in html tags? (according to your comment in bundle.properties) A button for copying those data would be helpful.

You are correct about the cause, but skimming the Java API, I found a better answer - I can use a JEditorPane instead.  I think that will allow the colors to be preserved when pasting the data into a fancy editor like WordPad, Microsoft Word, or OpenOffice Writer.

> Another thing, the reactor temperature. I don't think the current displayed colors of reactor temperature is proper for all designs, but I don't have a clear idea how they should be changed since whether it is beneficial for the reactor temperature to be higher or not highly depends on what the designer want. For pure uranium/thorium designs it is better to have a lower max temperature, while for a MOX reactor it might be better to have a higher max temperature. Hybrid reactors get more complex with this.

Uranium/thorium rods have the same outputs regardless of reactor temperature, so it seems to me having a higher reactor temperature is generally better for a mox/naquadah reactor regardless of whether there are also uranium/thorium rods included

> The "Components replaced" data seems to be missing.

Ah, good catch.  I will see about adding that.

**Comment by MauveCloud** [comment] 2019-04-09 16:21
> Then i think if the in-grid reactor has a max temperature that is higher than 85% while the in-tab one hasn't, the temperature of the one in-grid should be in red, and if the in-tab one is higher than 85% while the in-grid one hasn't, then the in-tab temperature should be green.

I have two problems with that:
1. None of the other comparison lines separately color-code the in-grid or in-tab value, just the difference (or the whole line based on the difference, in the case of materials and components).  Why should the max temperature be singled out and treated differently?
2. Max temperature over 85% is always a bad thing, because of the external effects - the lava can destroy the reactor pressure vessels around a fluid reactor, converting it to an EU reactor, or destroy the redstone circuitry keeping an EU reactor active.  (maybe there's some form of redstone circuitry immune to this, but idk what that would be).  Differences in time to reach thresholds for external effects (if either design reached them during simulation, rather than by initial temperature) are already shown in the comparison.

**Comment by KrisBigK** [comment] 2019-04-10 13:03
1. It is just to make it more obvious since temperatures above 85% is bad.
2. On 1.12.2 the pressure vessels won't be turned into lava (I saw that somewhere on the forum but I can't find it now), and the redstone circuitry is very simple.
![2019-04-10_18 40 40](https://user-images.githubusercontent.com/34199560/55880773-02391300-5bd4-11e9-910f-5769d9e51b8a.png)

**Comment by MauveCloud** [comment] 2019-04-10 18:05
>> and if the in-tab one is higher than 85% while the in-grid one hasn't, then the in-tab temperature should be green.
>     1. It is just to make it more obvious since temperatures above 85% is bad.

That makes some sense, but then why were you suggesting making the in-tab temperature green when it was over 85%?

>     2. On 1.12.2 the pressure vessels won't be turned into lava (I saw that somewhere on the forum but I can't find it now), and the redstone circuitry is very simple.

Whoever said that on the forum was mistaken - I've tried it with build 111, and there's nothing in the changelog to indicate newer builds would be different:
![2019-04-10_09 06 14](https://user-images.githubusercontent.com/8942955/55901195-b2c7f800-5b7d-11e9-9c6f-bbd003413129.png)

I tried an approximation of your design (using sandstone instead of grass and polished andesite), and it seems to work, but I don't understand why - looking at decompiled source, I would expect it to eventually replace the block between the redstone dust and the reactor with lava.

**Comment by KrisBigK** [comment] 2019-04-10 23:11
> and if the in-tab one is higher than 85% while the in-grid one hasn't, then the in-tab temperature should be green.

That's my fault. The in-grid one should be green.

> Whoever said that on the forum was mistaken - I've tried it with build 111, and there's nothing in the changelog to indicate newer builds would be different

Did you try replacing all pressure vessels with reactor access blocks like fluid port, access hatch, etc? From my tests those seems unaffected.

> I tried an approximation of your design (using sandstone instead of grass and polished andesite)

I'm not using andesite. The block is actually a CF wall.

**Comment by MauveCloud** [comment] 2019-04-11 04:32
> I'm not using andesite. The block is actually a CF wall.

Sorry, I don't normally use construction foam (also I use the Sphax PureBDCraft texture pack when actually playing instead of just testing), so I misindentified it.  Also, extended testing revealed that CF wall is _not_ immune to being replaced by lava.

> Did you try replacing all pressure vessels with reactor access blocks like fluid port, access hatch, etc? From my tests those seems unaffected.

Yes, as far as I can tell, they're immune, probably because they actually have tile entities (as suggested by the internal name "ic2:te", whereas the pressure vessels have internal name "ic2:resource").  However, the "reactor access blocks" as you call them each require 8 pressure vessels to craft, so instead of 148.75 lead (for a basic outer hull with one access hatch, one redstone port, and one fluid hatch), it would take 980 lead to build an outer hull entirely out of reactor access blocks.

**Comment by KrisBigK** [comment] 2019-04-12 12:39
Using the feature that ic2:te blocks won't be replaced by lava, it is possible to control an EU reactor by controlling the timings for the splitter cable and setting the redstone behavior of the MFSU that has 3 cables connected to it to "Emit if partially filled". Reactor automation is also possible by using the compact item buffer as an item puller.

**Comment by MauveCloud** [comment] 2019-04-12 16:57
Interesting trick, but I think I've added the sub-features you wanted in v2.3.4, closing issue now.

**Closed by MauveCloud** 2019-04-12 16:57 UTC
Labels: fixed in dev
