### ISSUE TITLE
Subnormal min EU/efficiency before depletion of the first rod

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#76] opened 2019-08-31 13:29 UTC
![image](https://user-images.githubusercontent.com/34199560/64064573-e80cd980-cc35-11e9-8c1d-154bacc13765.png)

erp=XOtKn69Rd0aZ7/1wo6sFPv5gXVswhYZcUEeqnUE/fvbUeZ1dgjZjgiwtS3E/HITIAQ==

I see no reason why the minimum EU/t displayed is 395.96 EU/t while the reactor temperature is constant.

**Comment by MauveCloud** [comment] 2019-08-31 17:25
I figured out why: using the CSV output, I can tell that the simulation considers the upper fuel rod to break during the last tick, causing the lower fuel rod to have reduced output on that tick.

As far as I can tell looking at decompiled IC2 source, this is accurate (rod depletion is checked as it iterates through the grid, not as a separate pass), though confirming it in-game would be a challenge - expected behavior based on the simulation would be for it to drop slightly at the very last reactor tick, then drop to zero after that.

**Comment by KrisBigK** [comment] 2019-09-01 01:57
With the help of NBTExplorer I wrote a command to get damaged fuel rods:
`/give @p ic2:dual_mox_fuel_rod 1 0 {advDmg:9995}`

And it is confirmed - the output _is_ lower than expected output in the last tick.

![2019-09-01_09 48 58](https://user-images.githubusercontent.com/34199560/64070823-2ccc5b00-cc9e-11e9-97e1-e31ec36c5cf6.png)
![2019-09-01_09 49 36](https://user-images.githubusercontent.com/34199560/64070824-2f2eb500-cc9e-11e9-918a-3ad0d173ee6d.png)
![2019-09-01_09 49 28](https://user-images.githubusercontent.com/34199560/64070825-305fe200-cc9e-11e9-8b34-1624fabf492e.png)

Also filed a bug report: https://bt.industrial-craft.net/view.php?id=2614

BTW I won't have time until Sunday. Sorry about that.

**Comment by MauveCloud** [comment] 2019-09-01 03:37
I'm predicting the IC2 devs will close that bug as "works as intended" (or whatever equivalent status their tracker uses), but since the planner's behavior matches the game's behavior in regards to this detail, I'm closing this one.  If my prediction is wrong and they decide to change IC2's in-game behavior, please re-open this bug at that time.

**Closed by MauveCloud** 2019-09-01 03:37 UTC
